# Dvojrozmerná a n-rozmerná náhodná premenná

## Štatisticky nezávislé premenné

Hodnoty niekoľkých meraných veličín nameraných v jednom čase môžeme pokladať za viacrozmernú náhodnú premennú reprezentovanú vektorom pozostávajúcim z $n$ náhodných premenných (<i>multivariate distribution</i>), ktoré môžu byť vzájomne závislé. Pre takýto vektor môžeme definovať funkciu hustoty pravdepodobnosti, funkciu rozdelenia pravdepodobnosti a maticu kovariancie, ktorá popisuje mieru závislosti jednotlivých zložiek vektora.\\
  
Ak $X$ a $Y$ sú <b>dve</b> náhodné premenné (<i>bivariate distribution</i>) ktorých distribučné funkcie sú definované ako

\begin{equation}
F_{X}(x) = P(X \leq x)
\end{equation}

\begin{equation}
F_{Y}(y) = P(Y \leq y)
\end{equation}

potom pre $X \leq x$ a $Y \leq y$ môžeme definovať viacrozmernú distribučnú funkciu (<i>joint probability distribution function</i>) ako

\begin{equation}
\nonumber
F_{XY}(x,y) = P(X \leq x, Y \leq y)   
\end{equation}

Podobne ako v jednorozmernom prípade môžeme definovať vlastnosti $F_{XY}(x,y)$

\begin{equation} 
F_{XY}(x,y) \in [0, 1]
\end{equation} 

\begin{equation} 
F_{XY}(x, -\infty) = F_{XY}(-\infty,y) = 0
\end{equation} 

\begin{equation} 
F_{XY}(\infty, \infty) = 1 
\end{equation} 

\begin{equation} 
F_{XY}(a,c) \leq F_{XY}(b, d) \quad \text{ak} \: a \leq b \: \text{a} \: c \leq d 
\end{equation} 

\begin{equation} 
P(a <x \leq b, c< y \leq d) = F_{XY}(b,d) + F_{XY}(a,c) - F_{XY}(a,d) - F_{XY}(b,c)
\end{equation} 

\begin{equation} 
F_{XY}(x, \infty) = F_X(x) 
\end{equation} 

\begin{equation} 
F_{XY}(\infty, y) = F_Y(y) 
\end{equation} 

Viacrozmerná funkcia hustoty pravdepodobnosti (<i>joint probability density function></i>) je definovaná ako

\begin{equation}
f_{XY}(x,y) = \frac{\partial^2 F_{XY}(x,y)}{\partial x \partial y}  
\end{equation}

pre ktorú môžeme na základe vyšie uvedeného definovať nasledujúce vzťahy

\begin{equation} 
F_{XY}(x,y) = \int\limits_{-\infty}^x \int\limits_{-\infty}^y f_{XY}(z_1, z_2) \, d z_1 \, d z_2  
\end{equation}

\begin{equation}
f_{XY}(x,y) \geq 0
\end{equation}

\begin{equation}
\int\limits_{-\infty}^\infty \int\limits_{-\infty}^\infty f_{XY}(x, y) \, d x \, d y =1
\end{equation}

\begin{equation}
P(a <x \leq b, c< y \leq d) = \int\limits_c^d \int\limits_a^b f_{XY}(x, y) \, d x \, d y
\end{equation}



\begin{equation}
f_X(x) = \int\limits_{-\infty}^{\infty} f_{XY}(x, y) \, d y
\end{equation}


\begin{equation}
f_Y(y) = \int\limits_{-\infty}^{\infty} f_{XY}(x, y) \, d x
\end{equation}

Ak udalosti spôsobujúce zmeny hodnoty jednej náhodnej premennej nemajú vplyv na pravdepodobnosť zmien druhej, sú tieto premenné štatisticky nezávislé a spĺňajú potom nasledujúce podmienky 

\begin{equation}
P(X \leq x, Y \leq y) =  P(X \leq x) P(Y \leq y)  
\end{equation}

a pre ich funkcie rozdelenia pravdepodobnosti a hustoty pravdepodobnosti platí

\begin{equation}
F_{XY}(x,y) = F_{X}(x) F_{Y}(y)
\end{equation}

\begin{equation}
f_{XY}(x,y) = f_{X}(x) f_{Y}(y)
\end{equation}

## Štatisticky závislé premenné

Viacrozmerné (<i>multivariate<i>) reprezentuje rozdelenie pre vektor niekoľkých náhodných premenných, ktorých štatistické vlastnosti môžu byť vzájomne závislé. Mieru vzájomnej závislosti určuje kovariancia (\textit{covariance = correlated variance}), t.j. ako sa korelované odchýlky dvoch premenných vzájomne menia jedna od druhej. Kovariancia pre dve náhodné premenné $X$, $Y$ je definovaná ako

\begin{equation}
Cov[X,Y] = E[(X-\mu_x)(Y-\mu_y)] 
\end{equation}

\begin{equation}
= E[XY] - \mu_y E[x] - \mu_x E[Y] + \mu_x \mu_y 
\end{equation}

\begin{equation}
= E[XY] - \mu_x \mu_y
\end{equation}

Pre viacrozmernú náhodnú premennú X definovanú v tvare sĺpcového vektora

\begin{equation}
X=\begin{bmatrix}
   X_{1}    \\
   X_{2}    \\
   \vdots   \\
   X_{n}
\end{bmatrix}
\end{equation}

môžeme definovať vektor stredných hodnôt

\begin{equation}
E[X]=\begin{bmatrix}
E[X_1]  \\
E[X_2]  \\
\vdots  \\
E[X_p]
\end{bmatrix}
\qquad
E[X_i] = \frac{1}{N} \sum_{k=1}^N x_i^k = \mu_i
\qquad
\text{(Pozn. } k \text{ je súčtový index)}
\end{equation}

a maticu kovariancie

\begin{equation}
Cov[X] = \begin{bmatrix}
Var\left[X_{1}\right] & Cov\left[X_{1}, X_{2}\right] & \cdots & Cov\left[X_{1}, X_{p}\right] \\ 
\\
Cov\left[X_{2}, X_{1}\right] & Var\left[X_{2}\right] & \cdots & Cov\left[X_{2}, X_{p}\right] \\ 
\\
\vdots & \vdots & \ddots & \vdots \\ 
\\
Cov\left[X_{p}, X_{1}\right] & Cov\left[X_{p}, X_{2}\right] & \cdots & Var\left[X_{p}\right]
\end{bmatrix} 
\end{equation}

kde

\begin{equation}
Var[X_i] = E[(X_i - \mu_i)^2]= \frac{1}{N} \sum_{k=1}^N (x_i^k - \mu_i)^2 = \sigma_{X_i}^2 = \sigma_i^2
\end{equation}

\begin{equation}
Cov[X_i, X_j] = E[(X_i - \mu_i)(X_j - \mu_j)]= \frac{1}{N} \sum_{k=1}^N (x_i^k - \mu_i)(x_j^k - \mu_j) = \sigma_{X_i X_j} = \sigma_{i j}
\end{equation}

V alternatívnom jednoduchšom značení (v kontexte $\Sigma$ nie je označenie pre sumu, ale pre veľké grécke písmeno Sigma) môžeme výrazy pre strednú hodnotu a kovarianciu prepísať do tvaru:

\begin{equation}
\boldsymbol\mu=\begin{bmatrix}
\mu_{1}  \\
\mu_{2}  \\
\vdots   \\
\mu_{n}
\end{bmatrix}
\qquad
\boldsymbol\Sigma = \begin{bmatrix}
\sigma_1^2 & \sigma_{1,2} & \cdots & \sigma_{1,p} \\
\\ 
\sigma_{2,1} & \sigma_2^2 & \cdots & \sigma_{2,p}\\ 
\\
\vdots & \vdots & \ddots & \vdots \\ 
\\
\sigma_{p,1} & \sigma_{p,2} & \cdots & \sigma_p^2
\end{bmatrix} 
\end{equation}

Normovaný korelačný koeficient s rozsahom hodnôt $[-1, 1]$ dvoch skalárnych náhodných premenných $X$ a $Y$ je definovaný ako
\begin{equation}
\rho_{XY} = \frac{\sigma_{XY}}{\sigma_X \: \sigma_Y}
\end{equation}

In [1]:
%reset -f  
from numpy import *

# Priklad - Vypocet parametrov n-rozmernej premennej

x1 = [-2.1, -1.0,  4.35,  9.0, 6.3]
x2 = [ 3.0,  1.1,  0.12,  4.2, 7.2]
x3 = [ 2.0,  1.1,  0.12, -1.9, 3.4]
X = vstack((x1,x2,x3))                      # stlpcovy vektor X = [x1,x2,x3]^T

print('Mean        ', mean(X))              # mean vsetkych prvkov, vysledok skalar
print()

print('Mean,  ax=1 \n', mean(X, axis=1))    # mean v smere horizontalnej osi (po riadkoch)
print()                                     # vysledok vektor [m1, m2, m3]

print('Mean,  ax=0 \n', mean(X, axis=0))    # mean v smere vertikalnej osi (po stlpcoch)
print()                                     # vysledok vektor [m1, m2, m3, m4, m5]

print('Covariance  \n', cov(X))             # matica kovariancie Sigma

print()
print('Norm. covariance\n',  corrcoef(X))   # normovana matica kovariancie R

Mean         2.45933333333

Mean,  ax=1 
 [ 3.31   3.124  0.944]

Mean,  ax=0 
 [ 0.96666667  0.4         1.53        3.76666667  5.63333333]

Covariance  
 [[ 22.5605    6.14495  -4.0203 ]
 [  6.14495   7.72688   2.24478]
 [ -4.0203    2.24478   3.98468]]

Norm. covariance
 [[ 1.          0.46541664 -0.42402101]
 [ 0.46541664  1.          0.40455258]
 [-0.42402101  0.40455258  1.        ]]
